kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels: 
   app: postgres
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.5
        imagePullPolicy: "IfNotPresent"
        env: 
        - name: POSTGRES_DB 
          value: postgresdb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: adminS3cret
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: myvolume
          mountPath: /var/lib/postgresql/data
      volumes:
          # mapped to the PVC
        - name: myvolume
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: postgres
  labels:
    app: postgres
spec: 
  ports:
    - port: 5432  
  selector: 
    app: postgres
  type: LoadBalancer    